.catalog:
  name: "JupyterHub: multi-user Jupyter notebook server "
  version: "1.2"
  description: "The Jupyter Notebook is a web application that allows you to create and share documents that contain live code, equations, visualizations and explanatory text. Uses include: data cleaning and transformation, numerical simulation, statistical modeling, machine learning and much more."
  uuid: jupyterhub-0
  questions:
    - variable: "public_port"
      type: "int"
      required: true
      default: "1080"
      label: "Public Port"
      description: "Port that JupyterHub will listen on"
jupyterhub:
  scale: 1
